all:
  children:
    spines:
      hosts:
        spine1:
          ansible_host: 172.20.20.10
    leaves:
      hosts:
        leaf1:
          ansible_host: 172.20.20.11
        leaf2:
          ansible_host: 172.20.20.12
  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
