all:
  children:
    spines:
      hosts:
        spine1:
          ansible_host: 172.20.20.10
    leaves:
      hosts:
        leaf1:
          ansible_host: 172.20.20.11
        leaf2:
          ansible_host: 172.20.20.12
  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_connection: network_cli
    ansible_network_os: nokia.srlinux.srlinux
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
