name: Test GitHub Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Test basic commands
      run: |
        echo "Testing GitHub Runner!"
        whoami
        pwd
        ls -la
        
    - name: Test Python
      run: |
        python3 --version
        pip3 --version
        
    - name: Test Docker (no sudo needed)
      run: |
        docker --version
        docker ps
        
    - name: Test ContainerLab
      run: |
        containerlab version
